# Generated by Django 2.0.1 on 2018-01-15 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BCM', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagebycountry',
            name='default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(max_length=2),
        ),
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.SlugField(max_length=2),
        ),
    ]
